#!/bin/bash
clear

echo -e "$y                  MENU UTAMA $wh"
echo -e "$y            VPN PREMIUM by Kereaktif TROJAN GO $wh"
echo -e "$y-------------------------------------------------$wh"
echo -e "$yy 1$y.  Buat Akun Trojan GO $wh"
echo -e "$yy 2$y.  Hapus Akun Trojan GO$wh"
echo -e "$yy 3$y.  Perpanjang Akun Trojan GO"
echo -e "$yy 4$y.  Restart Trojan GO"
echo -e "$yy 5$y.  Reboot VPS"
echo -e "$y-------------------------------------------------$wh"
read -p "Select From Options [ 1 - 5 ] : " menu
case $menu in
1)
clear
ak
;;
2)
clear
del
;;
3)
clear
renew
;;
4)
clear
refresh
;;
5)
clear
reboot
;;
*)
clear
menu
;;
esac
